#!/bin/sh
ZUSER=zope:zope
CPS_HOME=/opt/cps-3.5
INSTANCE=/var/opt/cps-3.5/test-instance
RC_SCRIPT=zope-cps-test
PYTHON=python2.4

case "$1" in
  abort-deconfigure|abort-upgrade)
    ;;
  abort-remove)
  ;;
  configure)
    # some previous versions did not clean .pyc files properly
    rm -rf $CPS_HOME/Products/Five
    find $CPS_HOME/Products -name '*.pyc' -delete

    # Byte compiling
    $PYTHON $CPS_HOME/bin/compilezpy.py $CPS_HOME/Products > /dev/null

    # Instance upgrade / creation
    if [ -d $INSTANCE ]; then
	echo "Found existing instance at $INSTANCE"
	upscript=$INSTANCE/bin/deb_upgrade
	echo "Upgrading via $upscript"
	exec $upscript $2
    else
        echo Creating Zope/CPS instance at $INSTANCE
        $CPS_HOME/bin/mkcpsinstance --posix-owner=$ZUSER -u admin:admin $INSTANCE

	ln -s $CPS_HOME/Products/CPSDefault/themes $INSTANCE/cps-themes
        echo Setting up startup script
        ln -s $INSTANCE/bin/zopectl /etc/init.d/zope-cps-test
        update-rc.d -f $RC_SCRIPT start 92 2 3 4 5 . stop 92 0 1 6 .
    fi
    echo "Starting Zope/CPS test instance (listens on port 6500)"
    /etc/init.d/$RC_SCRIPT start

    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

