#!/bin/sh
ZUSER=zope:zope
INSTANCE=/var/opt/cps-3.5/test-instance
CPS_HOME=/opt/cps-3.5

case "$1" in
  abort-deconfigure|abort-upgrade)
    ;;
  abort-remove)
  ;;
  configure)
    if [ -d $INSTANCE ]; then
	echo "Nothing to configure (found existing instance)"
    fi
    echo Creating Zope/CPS instance at $INSTANCE
    $CPS_HOME/bin/mkcpsinstance --posix-owner=$ZUSER -u admin:admin $INSTANCE
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

