#!/bin/sh
RC_SCRIPT=zope-cps-test

case "$1" in
  failed-upgrade)
  ;;
  upgrade|remove|deconfigure)
     script=/etc/init.d/$RC_SCRIPT
     if [ -f $script ]; then
       exec $script stop
     fi
  ;;
  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

